export const GET_TRANSACTION_TYPE_REQUEST = "GET_TRANSACTION_TYPE_REQUEST";
export const GET_TRANSACTION_TYPE_SUCCESS = "GET_TRANSACTION_TYPE_SUCCESS";
export const GET_TRANSACTION_TYPE_FAILURE = "GET_TRANSACTION_TYPE_FAILURE";
